import { Header } from "@/components/header"
import "./globals.css"
import { Footer } from "@/components/footer"
import { Providers } from "@/components/providers"
import { cn } from "@/lib/utils"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata, Viewport } from "next"
import type { ReactNode } from "react"

const TITLE = "Create Next App"
const DESCRIPTION = "Generated by create next app"

export const metadata: Metadata = {
	title: TITLE,
	description: DESCRIPTION,
	openGraph: {
		title: TITLE,
		description: DESCRIPTION,
		type: "website"
	}
}

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
	themeColor: [
		{ media: "(prefers-color-scheme: light)", color: "0 0% 100%" },
		{ media: "(prefers-color-scheme: dark)", color: "222.2 84% 4.9%" }
	]
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"font-sans",
					"antialiased",
					GeistSans.variable,
					GeistMono.variable
				)}
			>
				<div
					className={cn("relative", "h-screen", "w-full", "overflow-hidden")}
				>
					<div className={cn("absolute", "inset-0")}>
						<div
							className={cn(
								"absolute",
								"inset-0",
								"bg-gradient-to-tr",
								[
									"from-slate-100",
									"to-slate-300",
									"dark:from-slate-950",
									"dark:to-slate-800"
								],
								"p-4"
							)}
						>
							<Providers attribute="class" defaultTheme="system" enableSystem>
								<Header />
								<main
									className={cn(
										["mt-24", "mb-24"],
										"flex",
										"justify-center",
										"gap-y-4"
									)}
								>
									{children}
								</main>
								<Footer />
							</Providers>
						</div>
					</div>
				</div>
			</body>
		</html>
	)
}
